### ISSUE TITLE
document xrdp integration

### ISSUE THREAD

**Issue by kbucheli** [matt335672/nest-systemd-user#5]
Hi

Would it be possible to document how this tool can be retro-fitted to xrdp v0.9.x installations?

Thanks

Konrad

**Comment by matt335672** [comment]
It's a good point. There are probably quite a few rough edges to this still anyway.

In the absence of anything better you could start with [this comment](https://github.com/neutrinolabs/xrdp/issues/2491#issuecomment-1405224163) which from memory should do the job.

**Comment by akarl10** [comment]
Just made a MR for this (#6) and made reconnectwm.sh actually work in this context.
Else it is essentially the comment above put in README.md

**Comment by akarl10** [comment]
@kbucheli do you think the updated Readme (along with a slightly updated version of the tool) might be enough for a documentation how to use this tool with xrdp?

**Comment by kbucheli** [comment]
Yes, I could make it work. Thank you very much!
