### ISSUE TITLE
Test this on RHEL8.9 and RHEL9.4 with xrdp 0.9.20

### ISSUE THREAD

**Issue by vongillus** [matt335672/nest-systemd-user#7]
I try to run this on a test system but it doesn't seem to work. I have copied the file to /etc/xrdp and modified both startwm and startwm-bash scripts but the behavior is still the same.

Reading the snippet code, I don't really understand what does eval "`${0%/*}/systemd_user_context.sh init -p $$`" is doing. I think this part is not working on RHEL8.9 because if I change to eval "`/etc/xrdp/systemd_user_context.sh init -p $$`" it seems to work.

Any idea what is wrong there?

And thanks a lot for trying to get around systemd limitations. Going is the direction "no multi user" on Linux anymore is very sad!!

**Comment by vongillus** [comment]
Actually I can answer myself. So ${0%/*} is getting the script directory. But in RHEL the script starts from /usr/libexec/xrdp/startwm.sh and therefore it won't start the /etc/xrdp/systemd_user_context.sh. So I moved the systemd_user_context.sh to /usr/libexec/xrdp and it works. I didn't find yet any issue and I am using XFCE as desktop.

**Comment by matt335672** [comment]
Thanks for that @vongillus - it's a useful observation.

Is this an improvement:-

https://github.com/matt335672/nest-systemd-user/blob/update_readme/README.md

**Comment by vongillus** [comment]
Perfect @matt335672 ! Just for your information, I also tested this on RHEL9.4/xrdp 0.9.25 and it works so far. That's really something which saves me a lot of trouble, great work!

**Comment by matt335672** [comment]
Thanks for the feedback - I'll merge that update then.
